### ISSUE TITLE
“Bill_Yang骚话集” | pointedpoints' blog

### ISSUE THREAD

**Issue by pointedpoints** [pointedpoints/Comments_gitalk#1]
https://pointedpoints.github.io/2019/07/17/%E2%80%9CBill-Yang%E9%AA%9A%E8%AF%9D%E9%9B%86%E2%80%9D/#more 

 应某小姐姐要求，我们把那个Bill挂起来

**Comment by BillYang2016** [comment]
(╯‵□′)╯︵┻━┻
